# Generated by Django 3.2.6 on 2021-08-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internapp', '0002_auto_20210811_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(default='Neutral', max_length=10),
        ),
    ]
